### ISSUE TITLE
Add overflow:hidden to columns

### ISSUE THREAD

**Issue by erwstout** [erwstout/ginger#10]
Firefox doesn't listen to flex-basis values, for instance if `flex-basis: 50%` and contains a large image, etc.. it expands. Adding overflow:hidden fixes the issue.

**Comment by erwstout** [comment]
Fixed with `0.3.2`

**Comment by canfie1d** [comment]
Oh I literally just ran into this, @buschschwick.

Firefox (and soon to be Chrome) need `min-width : 0` on columns. Without it Firefox sets `min-width: -moz-min-content` and Chrome sets `min-width : auto` on any column with an image in it.

**Comment by erwstout** [comment]
Okay, have you tested on `0.3.2` yet? Either way, I can add that as a property for columns.

**Comment by erwstout** [comment]
Added `min-width: 0` to all columns in version `0.3.3`
