### ISSUE TITLE
Add negative margin on nested rows

### ISSUE THREAD

**Issue by bebaps** [erwstout/ginger#35]
Currently nested rows get indented. This is due to the padding that is set on the columns. Easy way to fix this is just to have any nested row have a negative margin that is equal to whatever the column padding is.

**Comment by erwstout** [comment]
Good idea, thanks!

**Comment by erwstout** [comment]
Added to `release/2.0` with commit 106928de681f6ece1fdd3d040d6df4cd2d822074
