### ISSUE TITLE
Add default styles for :before, :after, or add namespaces

### ISSUE THREAD

**Issue by bebaps** [erwstout/ginger#41]
This should only apply for Factor1 projects but may be useful beyond. In particular, these older projects that are already using Foundation or Kube or whatever. These typically already have a `container` and `row` class assigned, so adding in Ginger doesn't always work out of the box. The same is true for some resets that use

```
*:before,
*:after {
    ...code...
}
```

or even

```
*:before,
*:after {
    content: ' ';
    display: table;
}
```

as Ginger has now inherited those styles and may lead to problems.

Maybe add default styles to counter this behavior, or consider namespacing the classes.

**Comment by erwstout** [comment]
We kind of talked about this issue before hand in office, but I think any time you add two different kinds of frameworks there would be issues that would need to be sorted out, so I'm not really sure if adding something Ginger would be relevant so I'm just going to close this for now.
