### ISSUE TITLE
"Column Counts for Different Breakpoints" documentation

### ISSUE THREAD

**Issue by bebaps** [erwstout/ginger#51]
May be a good idea to update the documentation to reflect the desktop down nature of the grid, and to make that a bit more clear. 

To recap what I was showing you earlier, I wanted a column to be 12 columns up until the large breakpoint, and then 6 columns. I was not aware of the nature of the grid, and that I needed think of the grid as being 6 columns until it was down to medium (and then small), and then it would be 12 columns.

Since the medium breakpoint inherits the desktop column styles instead of the mobile column styles, this can be a point of confusion that could need clarification.

**Comment by erwstout** [comment]
Updated with commit f55420c
