### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by bebaps** [erwstout/ginger#52]
Documentation shows
```
<div class="lg-only--block">
  <!-- Content -->
</div>
```
but it should be
```
<div class="lg-only lg-only--block">
  <!-- Content -->
</div>
```

**Comment by erwstout** [comment]
Ah, okay. So upon looking at it - I made it a little more clear, but I think you may have misread it. The html snippet you're referring to is about adjusting the `display` property of the element.

For instance, adding `.lg-only--block` will change that element's `display` property to `block`.
