### ISSUE TITLE
Adjust breakpoints

### ISSUE THREAD

**Issue by bebaps** [erwstout/ginger#54]
Due to the desktop down nature of the grid the breakpoints should be adjusted by 1px. This is because of the `max-width` used for the media queries, `max-width: 1024px` when it should be `max-width: 1023px`.

Change the `$small-breakpoint` to `39.938em` and `$medium-breakpoint` to `63.938em`. These values assume a root font size of 16px.

**Comment by erwstout** [comment]
Going to leave this as is for now, since it allows `md-col-` to target iPad, as well as the variables can be changed via `_settings.scss`
