### ISSUE TITLE
Add in breakpoint scss

### ISSUE THREAD

**Issue by mattada** [erwstout/ginger#59]
Not sure if this is hear and I couldnt find it, but leveraging a breakpoint in scss could come from a global mixin maybe? 

like
https://github.com/digitaledgeit/sass-breakpoints

or does ginger settings this cover it somehow?

**Comment by erwstout** [comment]
You can access breakpoint sizes like so:

```scss
@media screen and (max-width: $small-breakpoint) { };
```
